# Generated by Django 3.1 on 2020-09-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200923_0544'),
        ('posts', '0002_auto_20200923_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.genuser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('SECONDHAND', '중고장터'), ('YOGA', '요가'), ('PILATES', '필라테스'), ('MEETUP', '같이 운동해요'), ('ETC', '기타')], max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_path',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
