# Generated by Django 3.1 on 2020-09-24 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200923_0544'),
        ('posts', '0003_auto_20200923_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.genuser'),
        ),
    ]
