# Generated by Django 3.1 on 2020-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200924_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('중고장터', 'Secondhand'), ('요가', 'Yoga'), ('필라테스', 'Pilates'), ('같이_운동해요', 'Meetup'), ('기타', 'Etc')], max_length=10),
        ),
    ]
