# Generated by Django 3.1 on 2020-10-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201010_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img_path',
            new_name='img_path1',
        ),
        migrations.AddField(
            model_name='post',
            name='img_path2',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='img_path3',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='img_path4',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
