# Generated by Django 3.1 on 2020-09-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='img_path',
            field=models.FileField(max_length=500, null=True, upload_to=''),
        ),
    ]
