# Generated by Django 3.1 on 2020-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0005_diary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='img_path',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
