# Generated by Django 3.1 on 2020-09-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.FileField(blank=True, upload_to='user'),
        ),
    ]
