# Generated by Django 3.1 on 2020-10-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200923_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
