# Generated by Django 3.1 on 2020-10-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201020_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
    ]
