# Generated by Django 3.1 on 2020-10-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='voucherUser',
            field=models.ForeignKey(default='100', on_delete=django.db.models.deletion.CASCADE, to='bookings.voucheruser'),
        ),
    ]
