# Generated by Django 3.1 on 2020-10-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_userlesson_voucheruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlesson',
            name='voucherUser',
            field=models.IntegerField(),
        ),
    ]
