# Generated by Django 3.1 on 2020-09-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200922_0231'),
        ('bookings', '0002_remove_userlesson_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.adminuser'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.genuser'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.adminuser'),
        ),
        migrations.AlterField(
            model_name='voucheruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.genuser'),
        ),
    ]
