# Generated by Django 3.1 on 2020-10-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20201013_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlesson',
            old_name='voucherUser',
            new_name='voucher',
        ),
    ]
